; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27404.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\nimerkuloff\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
